services:
  - docker

install:
  - docker build -t ddiez/bedtools .

script:
  - docker run ddiez/bedtools bedtools

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push ddiez/bedtools;
    fi
